# -*- Makefile -*-
# :Project:  pxpy -- Makefile
# :Source:   $Source$
# :Created:  Sun, Apr 04 2004 00:13:57 CEST
# :Author:   Lele Gaifax <lele@nautilus.homeip.net>
# :Revision: $Revision$ by $Author, $Date$
# 

all:
	python Setup.py build_ext --inplace

clean:
	rm -f *.c *.o *.so *~ core
	rm -rf build
